# Default values for keycloak-resources.

keycloak:
  name: mykeycloak
  replicas: 1
  externalDatabase:
    enabled: true
    address: postgresql.decapod-db.svc.cluster.local # Shoud be FQDN
    port: 5432
    databaseName: keycloak
    username: keycloak
    password: keycloak
    superuserEnabled: true
  storageClassName: storage # Valid only if externalDatabase is false
  externalAccessEnabled: false

keycloakRealm: []
# - name: myrealm
#   displayName: "My Realm"

keycloakUser: []
# - name: "myuser"
#   firstName: "John"
#   lastName: "Doe"
#   email: "myuser@keycloak.org"
#   password: "12345"
#   realm: myrealm

keycloakClient: []
# - name: myclient
#   realm: myrealm
#   protocol: openid-connect
#   rootUrl: https://www.keycloak.org/app/
