{{- if .Values.fluentbitOperator.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fluentbit-operator.operator.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "fluentbit-operator.name" . }}-operator
{{ include "fluentbit-operator.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fluentbit-operator.name" . }}-operator
      release: {{ $.Release.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ template "fluentbit-operator.name" . }}-operator
{{ include "fluentbit-operator.labels" . | indent 8 }}
{{- if .Values.fluentbitOperator.podLabels }}
{{ toYaml .Values.fluentbitOperator.podLabels | indent 8 }}
{{- end }}
{{- if .Values.fluentbitOperator.podAnnotations }}
      annotations:
{{ toYaml .Values.fluentbitOperator.podAnnotations | indent 8 }}
{{- end }}
    spec:
{{- if .Values.fluentbitOperator.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.fluentbitOperator.nodeSelector | indent 8 }}
{{- end}}
    {{- if .Values.fluentbitOperator.priorityClassName }}
      priorityClassName: {{ .Values.fluentbitOperator.priorityClassName }}
    {{- end }}
      initContainers:
        - name: setenv
          image: "{{ .Values.image.init.repository }}:{{ .Values.image.init.tag }}"
          imagePullPolicy: "{{ .Values.image.init.pullPolicy }}"          
          command: 
          - sh
          - '-c'
          - /tmp/init-fluent-bit.env.sh
          volumeMounts:
          - name: env
            mountPath: /fluentbit-operator
          - name: dockersock
            readOnly: true
            mountPath: /var/run/docker.sock
          - name: {{ template "fluentbit-operator.name" . }}-bin
            readOnly: true
            mountPath: /tmp/init-fluent-bit.env.sh
            subPath: init-fluent-bit-env.sh
      containers:
        - name: {{ template "fluentbit-operator.name" . }}
          image: "{{ .Values.image.operator.repository }}:{{ .Values.image.operator.tag }}"
          imagePullPolicy: "{{ .Values.image.operator.pullPolicy }}"
          resources:
{{ toYaml .Values.fluentbitOperator.resources | indent 12 }}
          volumeMounts:
          - name: env
            mountPath: /fluentbit-operator
# {{- if .Values.fluentbitOperator.createCustomResource }}            
#           - name: fluentbit-bin
#             readOnly: true
#             mountPath: /tmp/pre-stop-hook-script.sh
#             subPath: pre-stop-hook-script.sh
#           lifecycle:
#             preStop:
#               exec:
#                 command:
#                   - bash
#                   - '-c'
#                   - /tmp/pre-stop-hook-script.sh
# {{- end}}
          # securityContext:
          #   allowPrivilegeEscalation: false
          #   readOnlyRootFilesystem: true
      volumes:
        - name: env
          emptyDir: {}
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: {{ template "fluentbit-operator.name" . }}-bin
          configMap:
            name: {{ template "fluentbit-operator.name" . }}-bin
            defaultMode: 365
{{- if .Values.fluentbitOperator.securityContext }}
      securityContext:
{{ toYaml .Values.fluentbitOperator.securityContext | indent 8 }}
{{- end }}
      serviceAccountName: {{ template "fluentbit-operator.operator.serviceAccountName" . }}
    {{- with .Values.fluentbitOperator.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.fluentbitOperator.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.fluentbitOperator.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}