{{- if and .Values.fluentbit.enabled }}
apiVersion: logging.kubesphere.io/v1alpha2
kind: FluentBitConfig
metadata:
  name: fluent-bit-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: v1.4.5
spec:
  service:
    parsersFile: parsers.conf
    # logLevel: debug
  inputSelector:
    matchLabels:
      logging.kubesphere.io/enabled: "true"
  filterSelector:
    matchLabels:
      logging.kubesphere.io/enabled: "true"      
  outputSelector:
    matchLabels:
      logging.kubesphere.io/enabled: "true"
{{- end}}